name: Deploy website

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    paths:
      - 'src/site/**' # React to site files changing
      - '.github/workflows/build.yml' # React to the workflow file itself changing

  workflow_dispatch: # Allow manual runs

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy the website

    steps:
      - name: Upload the website files as an artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/site/

      - name: Deploying the website to Github Pages
        uses: actions/deploy-pages@v4