name: Deploy website

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: master
    paths:
      - 'src/site/**' # React to site files changing
      - 'build_site.sh' # React to build file changing
      - '.github/workflows/deploy.yml' # React to the workflow file itself changing

  workflow_dispatch: # Allow manual runs

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy the website

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: "src/ChartGenerator/pnpm-lock.yaml"


      - name: Install pnpm dependencies
        run: pnpm install
        working-directory: src/ChartGenerator

      - name: Run build script
        run: ./build_site.sh

      - name: Upload the website files as an artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site_output

      - name: Deploying the website to Github Pages
        uses: actions/deploy-pages@v4